info:
  version: '@project.version@'
  stage: dev

server:
  port: '@server.port@'
  rest:
    port: '@server.rest.port@'
    endpoint: ch-manager

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: "localhost:29092"
    streams:
      application-id: wb-list
      client-id: wb-list-client

management:
  server:
    port: '@management.port@'
  metrics:
    export:
      prometheus:
        enabled: false
    tags:
      application: proxy-mocket-inspector
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

riak-config:
  address: localhost
  port: 8087
  bucket: wblist

retry:
  timeout: 2000
  max.attempts: 3

kafka:
  wblist:
    topic:
      command: "wb-list-command"
      event.sink: "wb-list-event-sink"
  correction-stream:
    enabled: true
    application-id: wb-list-correction-empty-list-name
    client-id: wb-list-correction-empty-list-name-client
