name: Build Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v4

      - name: Run Build Java
        uses: valitydev/action-jdk-build@v0.0.7
