name: Maven Deploy Artifact

on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  deploy:
    uses: valitydev/java-workflow/.github/workflows/maven-service-deploy.yml@v1
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      mm-webhook-url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
